# -*- mode: python ; coding: utf-8 -*-
# 单文件（onefile）打包：产出一个免安装、可直接双击运行的 semi-utils.exe

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('./templates', './templates'),
        ('./static', './static'),
        ('./config', './config'),
        ('./pyproject.toml', '.'),
        ('./exiftool', './exiftool'),
    ],
    hiddenimports=[
        'flask',
        'jinja2',
        'numpy',
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'pillow_heif',
        'loguru',
        'configparser',
        'click',
        'ctypes',
        '_ctypes',
        # 动态注册的处理器模块（importlib 字符串导入，PyInstaller 无法自动发现）
        'processor',
        'processor.core',
        'processor.filters',
        'processor.generators',
        'processor.mergers',
        'processor.types',
        'core',
        'core.configs',
        'core.util',
        'core.logger',
        'core.jinja2renders',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='semi-utils',
    icon='./static/logo.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
